line 97, in fieldnames
    self._fieldnames = next(self.reader)
                       ^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdf in position 51: invalid continuation byte

During handling of the above exception, another exception occurred:



process_csv
    input_file = row["input_file"]
                 ~~~^^^^^^^^^^^^^^
KeyError: 'input_file'
